# Generated by Django 4.2.6 on 2024-02-22 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('quote', models.CharField(max_length=50)),
                ('body', models.CharField(max_length=500)),
            ],
        ),
    ]
