# Generated by Django 5.0.2 on 2024-03-04 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_poem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookings',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='bookings',
            name='last_name',
        ),
    ]
